### ISSUE TITLE
Missing step for PATCH releases

### ISSUE THREAD

**Issue by Flix6x** [FlexMeasures/tsc#6]
Following [our release checklist](https://github.com/FlexMeasures/tsc/blob/update-release-checklist/RELEASE.md) led me to release the docker image for `lfenergy/flexmeasures:v0.14.1` with the wrong (older) code. I think the `docker compose build` step in the checklist may need to be listed for PATCH releases, too, instead of just being relevant for MAJOR and MINOR releases.

**Comment by nhoening** [comment]
It seems all testing is not mentioned under PATCH releases, but at least `make test` should happen there.

I'll re-arrange it.
