### ISSUE TITLE
Docker release step issues

### ISSUE THREAD

**Issue by Flix6x** [FlexMeasures/tsc#9]
I faced 2 issues with release steps involving Docker:

- `docker rmi flexmeasures-server flexmeasures-worker` gives `Error: No such image: flexmeasures-server` and likewise for the worker. Turning each dash into an underscore resolved this for me. Should this release step be updated accordingly?
- `docker tag flexmeasures-server lfenergy/flexmeasures:v0.15.1` gives `No such image: flexmeasures-server:latest`. Again, an underscore resolves this. Update the release step, or am I doing something wrong?

**Comment by nhoening** [comment]
I believe I changed those recently to suit me (so I did not have to replace). Might have to do with Docker Compose versions. We can only support one, let's take the latest. Here is mine:

```
% docker compose version  
Docker Compose version v2.20.2
```

**Comment by Flix6x** [comment]
Resolved by upgrading docker compose.
